- name: System Configuration
  hosts: localhost
  connection: local
  vars:
    config: "{{ lookup('file','config.yaml') | from_yaml }}"
  tasks:
    - name: Startup
      debug:
        msg: Starting system setup
    - name: Package Management 
      include_role:
        name: "src/packages"
