- name: Installing DNF Packages
  ansible.builtin.dnf:
    name: "{{ packages[item].dnf }}"
    state: latest
  loop: "{{ config.packages }}"

- name: Installing Flatpaks
  community.general.flatpak:
    name: "{{ packages[item].flatpak }}"
    state: present 
  loop: "{{ config.packages }}"
- name: Installing Rust
  ansible.builtin.shell: "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y"
  when: '"development" in config.packages'
