- name: Install shell items
  block:
    - name: Setup ZSH 
      ansible.builtin.dnf:
        name: "zsh"
        state: latest
    - name: Setup oh-my-zsh
      become: true
      become_user: aaditya
      ansible.builtin.shell: 'sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended'

    - name: Setup p10k, tmux and zshrc
      ansible.builtin.copy:
        src: shell/{{ item }}
        dest: "/home/{{ config.username }}"
        backup: yes
      loop:
        - .p10k.zsh
        - .zshrc
        - .tmux.conf

    - name: Setup vimrc and vim bundles
      ansible.builtin.copy:
        src: shell/{{ item }}
        dest: "/home/{{ config.username }}"
        backup: yes
      loop:
        - .vimrc

    - name: Setup vim/neovim directories
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "/home/{{ config.username }}/.config"
        backup: yes
      loop:
        - nvim

  when: 'config.config.install_shell'

- name: Install Dotfiles (Wayland)
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/home/{{ config.username }}/.config/"
    backup: yes
  loop: "{{ config_wayland }}"
  when: 'config.config.install_wayland'

- name: Install Dotfiles (Xorg)
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/home/{{ config.username }}/.config/"
    backup: yes
  loop: "{{ config_xorg }}"
  when: 'config.config.install_xorg'

- name: Install Dotfiles (All)
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/home/{{ config.username }}/.config/"
    backup: yes
  loop: "{{ config_all }}"
  when: "config.config.install_xorg or config.config.install_wayland"
